import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient, type HistoricalScope, type HistoricalStatus, type SourceLevel } from "../../app/generated/prisma";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL must be defined.");
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });

type Scope = HistoricalScope;
type Status = HistoricalStatus;
type Level = SourceLevel;

function relevanceDecision(id: string, scope: Scope, tags: string[], sensitive = false) {
  const level = scope === "GABON_INTERIOR" ? "L1_GABON_DIRECT" : scope === "DIASPORA" ? "L2_DIASPORA_GABONAISE" : "L1_GABON_DIRECT";
  const points = scope === "GABON_INTERIOR" ? 80 : scope === "DIASPORA" ? 70 : 90;
  return {
    content_id: id,
    score: points,
    level,
    flags: { is_sensitive: sensitive, requires_human_review: sensitive },
    score_breakdown: [{ signal: scope === "DIASPORA" ? "diaspora" : "gabon_direct", points: scope === "DIASPORA" ? 20 : 40, matchedTerms: tags }, { signal: "official_source", points: 20, matchedTerms: ["historical corpus"] }],
    routing: { primary_target: sensitive ? "HUMAN_REVIEW" : "AUTO_PUBLISH", secondary_targets: ["articles"], tags },
  };
}

const events: Array<{ id: string; title: string; period: string; exactDate?: string; description: string; historicalStatus: Status; sourceLevel: Level; scope: Scope; sensitive?: boolean }> = [
  { id: "history-event-peopling", title: "Peuplement ancien et migrations bantu au Gabon", period: "Ier millenaire av. J.-C. - XIXe siecle", description: "Les traditions orales, la linguistique et l'archeologie documentent des migrations bantu et la formation progressive de societes etablies dans l'espace gabonais.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR" },
  { id: "history-event-loango", title: "Royaume de Loango et echanges atlantiques", period: "XVIe - XIXe siecles", description: "Le royaume de Loango a participe aux reseaux politiques et commerciaux de la cote atlantique, incluant le territoire du Gabon actuel.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR" },
  { id: "history-event-french-protectorate", title: "Etablissement du protectorat francais", period: "1839-1843", exactDate: "1839-02-09", description: "Des traites conclus avec des autorites locales ouvrent la voie a l'implantation francaise sur l'estuaire du Gabon.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR" },
  { id: "history-event-libreville", title: "Fondation de Libreville", period: "1849", exactDate: "1849-06-01", description: "Libreville est fondee en 1849 pour accueillir des personnes liberees d'un navire negrier intercepte, episode central de l'histoire urbaine gabonaise.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR" },
  { id: "history-event-afrique-equatoriale", title: "Integration a l'Afrique equatoriale francaise", period: "1910", exactDate: "1910-01-15", description: "Le Gabon est integre a l'Afrique equatoriale francaise, federation coloniale francaise d'Afrique centrale.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR" },
  { id: "history-event-france-libre", title: "Ralliement du Gabon a la France libre", period: "1940", exactDate: "1940-11-12", description: "La campagne du Gabon conduit au ralliement du territoire a la France libre pendant la Seconde Guerre mondiale.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-brazzaville", title: "Conference de Brazzaville et evolutions politiques", period: "1944", exactDate: "1944-01-30", description: "La Conference de Brazzaville ouvre un cycle de reformes dans les territoires francais d'Afrique, dont le Gabon.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-territorial-assembly", title: "Mise en place de l'Assemblee territoriale", period: "1946", description: "La representation territoriale gabonaise s'organise dans le cadre de l'Union francaise et de ses institutions electorales.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-autonomous-republic", title: "Republique gabonaise autonome", period: "1958", exactDate: "1958-11-28", description: "Le Gabon devient une republique autonome au sein de la Communaute francaise apres le referendum de 1958.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-independence", title: "Independance de la Republique gabonaise", period: "1960", exactDate: "1960-08-17", description: "La Republique gabonaise accede a l'independance le 17 aout 1960.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "BOTH", sensitive: true },
  { id: "history-event-un-membership", title: "Admission du Gabon aux Nations unies", period: "1960", exactDate: "1960-09-20", description: "Le Gabon devient membre de l'Organisation des Nations unies apres son independance.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "BOTH" },
  { id: "history-event-1961-constitution", title: "Constitution de la Premiere Republique", period: "1961", exactDate: "1961-02-21", description: "Une constitution organise les institutions de la jeune Republique gabonaise.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-1964-crisis", title: "Crise politique de fevrier 1964", period: "1964", exactDate: "1964-02-18", description: "La crise de fevrier 1964 constitue un episode majeur de l'histoire politique gabonaise et fait l'objet d'analyses historiographiques multiples.", historicalStatus: "CONTROVERSIAL", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-oil-production", title: "Essor de la production petroliere", period: "Annees 1960-1970", description: "Le developpement de la production petroliere transforme durablement l'economie et les finances publiques du Gabon.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR" },
  { id: "history-event-one-party", title: "Mise en place du Parti democratique gabonais", period: "1968", exactDate: "1968-03-12", description: "Le Parti democratique gabonais est cree dans le contexte de l'instauration d'un systeme de parti unique.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-renovation", title: "Politique de renovation nationale", period: "Annees 1970", description: "Les politiques publiques de modernisation et d'infrastructures marquent la periode de croissance petroliere.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR" },
  { id: "history-event-national-conference", title: "Conference nationale souveraine", period: "1990", exactDate: "1990-03-23", description: "La Conference nationale de 1990 engage une transition vers le pluralisme politique et de nouvelles institutions.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-multiparty-constitution", title: "Constitution pluraliste de 1991", period: "1991", exactDate: "1991-03-26", description: "La revision constitutionnelle de 1991 consolide le multipartisme et redessine le cadre institutionnel.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-lope-world-heritage", title: "Inscription du parc de la Lope au patrimoine mondial", period: "2007", exactDate: "2007-07-01", description: "Le paysage culturel et naturel des ecosystems relictuels de la Lope-Okanda est inscrit au patrimoine mondial de l'UNESCO.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR" },
  { id: "history-event-gabon-emergent", title: "Lancement du Plan strategique Gabon emergent", period: "2009", description: "Le Plan strategique Gabon emergent structure une politique de diversification economique et de transformation nationale.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-national-parks", title: "Creation des parcs nationaux du Gabon", period: "2002", exactDate: "2002-08-30", description: "Le Gabon cree un reseau de treize parcs nationaux pour proteger ses ecosystemes forestiers et marins.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR" },
  { id: "history-event-2016-election", title: "Election presidentielle et crise post-electorale de 2016", period: "2016", description: "Les resultats de l'election presidentielle de 2016 et leurs suites font partie d'une histoire politique sensible documentee par des sources officielles et internationales.", historicalStatus: "CONTROVERSIAL", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-political-dialogue", title: "Dialogue politique national", period: "2017", description: "Le dialogue politique national reunit des acteurs gabonais autour de propositions institutionnelles apres la crise de 2016.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-covid", title: "Reponse nationale a la pandemie de COVID-19", period: "2020-2022", description: "Le Gabon met en place des mesures sanitaires, sociales et economiques pendant la pandemie de COVID-19.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "BOTH" },
  { id: "history-event-2023-transition", title: "Transition politique d'aout 2023", period: "2023", exactDate: "2023-08-30", description: "Les evenements du 30 aout 2023 ouvrent une phase de transition politique au Gabon, a documenter par des sources recoupees.", historicalStatus: "CONTROVERSIAL", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-national-dialogue", title: "Dialogue national inclusif de 2024", period: "2024", description: "Le dialogue national inclusif rassemble des participants autour de la refondation institutionnelle et politique du pays.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-constitutional-reform", title: "Reforme constitutionnelle de la transition", period: "2024", description: "Le processus de reforme constitutionnelle engage durant la transition fait l'objet de textes officiels et de debats publics.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "history-event-diaspora-associations", title: "Structuration des associations de diaspora gabonaise", period: "Annees 1990-2020", description: "Des associations de ressortissants gabonais se structurent dans plusieurs pays d'accueil autour de l'entraide, de la culture et de l'accompagnement administratif.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "DIASPORA" },
  { id: "history-event-student-mobility", title: "Mobilite internationale des etudiants gabonais", period: "Annees 2000-2020", description: "Les mobilites etudiantes vers l'Afrique, l'Europe et l'Amerique du Nord constituent un trait durable des parcours de formation gabonais.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "BOTH" },
  { id: "history-event-women-public-life", title: "Participation croissante des femmes a la vie publique", period: "1960-2020", description: "La participation des femmes gabonaises a la vie publique, associative, professionnelle et politique est documentee par des sources institutionnelles et académiques.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "BOTH", sensitive: true },
];

const figures: Array<{ id: string; fullName: string; category: string; biography: string; mainImpact: string; historicalStatus: Status; sourceLevel: Level; scope: Scope; sensitive?: boolean }> = [
  { id: "figure-leon-mba", fullName: "Leon Mba", category: "Homme d'Etat", biography: "Leon Mba est le premier president de la Republique gabonaise independante.", mainImpact: "Il dirige le pays durant les premieres annees de l'independance et participe a la mise en place des institutions nationales.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-omar-bongo", fullName: "Omar Bongo Ondimba", category: "Homme d'Etat", biography: "Omar Bongo Ondimba dirige le Gabon de 1967 a 2009.", mainImpact: "Sa longue presidence marque durablement les institutions, les relations internationales et l'economie gabonaises.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-rose-francine-rogombe", fullName: "Rose Francine Rogombe", category: "Femme d'Etat", biography: "Rose Francine Rogombe exerce la presidence par interim en 2009 en qualite de presidente du Senat.", mainImpact: "Elle assure la continuite institutionnelle pendant la transition de 2009.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-ali-bongo", fullName: "Ali Bongo Ondimba", category: "Homme d'Etat", biography: "Ali Bongo Ondimba est president de la Republique gabonaise de 2009 a 2023.", mainImpact: "Son mandat est associe au Plan strategique Gabon emergent et a des transformations economiques et institutionnelles debattues.", historicalStatus: "FACT", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-brice-oligui", fullName: "Brice Clotaire Oligui Nguema", category: "Homme d'Etat", biography: "Brice Clotaire Oligui Nguema dirige la transition ouverte en aout 2023.", mainImpact: "Il preside les institutions de transition et le processus de refondation nationale.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_A", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-jean-hilaire-aubame", fullName: "Jean-Hilaire Aubame", category: "Homme politique", biography: "Jean-Hilaire Aubame est une figure de la vie politique gabonaise avant et apres l'independance.", mainImpact: "Son parcours est notamment lie aux recompositions politiques des annees 1960.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-pierre-mamboundou", fullName: "Pierre Mamboundou", category: "Homme politique", biography: "Pierre Mamboundou est une figure de l'opposition politique gabonaise contemporaine.", mainImpact: "Il participe a l'installation du pluralisme et aux debats electoraux depuis les annees 1990.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-paul-mba-abessole", fullName: "Paul Mba Abessole", category: "Homme politique", biography: "Paul Mba Abessole est une personnalite politique et religieuse gabonaise.", mainImpact: "Il joue un role dans le pluralisme politique et les dynamiques electorales de la periode post-1990.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-andre-mba-obame", fullName: "Andre Mba Obame", category: "Homme politique", biography: "Andre Mba Obame est une figure politique gabonaise de la periode contemporaine.", mainImpact: "Son parcours contribue aux debats sur l'opposition et les processus electoraux.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-zita-oligui", fullName: "Zita Oligui Nguema", category: "Actrice sociale", biography: "Zita Oligui Nguema est engagee dans des initiatives sociales et de solidarite au Gabon.", mainImpact: "Elle illustre la place d'initiatives citoyennes et sociales dans l'action publique contemporaine.", historicalStatus: "OFFICIAL_POSITION", sourceLevel: "LEVEL_C", scope: "GABON_INTERIOR" },
  { id: "figure-pierre-savorgnan", fullName: "Pierre Savorgnan de Brazza", category: "Explorateur", biography: "Pierre Savorgnan de Brazza est un explorateur et administrateur francais lie a l'histoire coloniale de l'Afrique centrale.", mainImpact: "Son action est associee a la penetration coloniale francaise et doit etre lue avec le recul critique de l'historiographie contemporaine.", historicalStatus: "CONTROVERSIAL", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-raponda-walker", fullName: "Andre Raponda-Walker", category: "Religieux et ethnologue", biography: "Andre Raponda-Walker est un pretre et ethnologue gabonais, auteur de travaux sur les langues et cultures locales.", mainImpact: "Ses travaux constituent une reference pour l'etude des societes et traditions gabonaises.", historicalStatus: "ACADEMIC_ANALYSIS", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR" },
  { id: "figure-georges-rawiri", fullName: "Georges Rawiri", category: "Homme d'Etat", biography: "Georges Rawiri est une personnalite politique gabonaise ayant exerce plusieurs responsabilites gouvernementales et parlementaires.", mainImpact: "Il participe a la vie institutionnelle et diplomatique gabonaise de la seconde moitie du XXe siecle.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-martine-oussie", fullName: "Martine Oulabou", category: "Actrice culturelle", biography: "Martine Oulabou est associee a la valorisation de la culture gabonaise dans les espaces artistiques et communautaires.", mainImpact: "Son parcours represente les contributions culturelles de la diaspora gabonaise.", historicalStatus: "TESTIMONY", sourceLevel: "LEVEL_C", scope: "DIASPORA" },
  { id: "figure-pierre-claver-maganganga", fullName: "Pierre-Claver Maganga Moussavou", category: "Homme politique", biography: "Pierre-Claver Maganga Moussavou est une figure politique gabonaise engagee dans la vie partisane contemporaine.", mainImpact: "Il contribue aux debats politiques et institutionnels au Gabon.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
  { id: "figure-daniel-mengara", fullName: "Daniel Mengara", category: "Universitaire et ecrivain", biography: "Daniel Mengara est un universitaire et ecrivain gabonais actif dans les debats publics depuis la diaspora.", mainImpact: "Son parcours illustre les prises de parole intellectuelles et politiques de la diaspora gabonaise.", historicalStatus: "FACT", sourceLevel: "LEVEL_C", scope: "DIASPORA", sensitive: true },
  { id: "figure-theo-blaise-kounkou", fullName: "Theo Blaise Kounkou", category: "Musicien", biography: "Theo Blaise Kounkou est un musicien gabonais reconnu dans les musiques africaines contemporaines.", mainImpact: "Il contribue a la diffusion de la culture gabonaise dans des espaces internationaux.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "BOTH" },
  { id: "figure-pierre-akam", fullName: "Pierre Akam", category: "Entrepreneur culturel", biography: "Pierre Akam represente les initiatives entrepreneuriales et culturelles de Gabonais etablis hors du pays.", mainImpact: "Son parcours est retenu comme temoignage de l'engagement diasporique dans la promotion culturelle.", historicalStatus: "TESTIMONY", sourceLevel: "LEVEL_C", scope: "DIASPORA" },
  { id: "figure-laurent-owondo", fullName: "Laurent Owondo", category: "Ecrivain", biography: "Laurent Owondo est un ecrivain gabonais dont l'oeuvre est associee a la litterature africaine francophone.", mainImpact: "Son travail participe a la representation litteraire du Gabon au-dela de ses frontieres.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "BOTH" },
  { id: "figure-justin-koumba", fullName: "Justin Koumba", category: "Homme politique", biography: "Justin Koumba est une figure de la vie politique et parlementaire gabonaise.", mainImpact: "Il participe aux institutions representatives et aux debats publics nationaux.", historicalStatus: "FACT", sourceLevel: "LEVEL_B", scope: "GABON_INTERIOR", sensitive: true },
];

const archives: Array<{ id: string; title: string; actDate?: string; legalNature: string; sourceLevel: Level; documentUrl?: string; scope: Scope; sensitive?: boolean }> = [
  { id: "archive-treaty-1839", title: "Traite de protectorat sur l'estuaire du Gabon", actDate: "1839-02-09", legalNature: "Traite de protectorat", sourceLevel: "LEVEL_A", documentUrl: "https://gallica.bnf.fr/", scope: "GABON_INTERIOR" },
  { id: "archive-decree-1849", title: "Archives relatives a la fondation de Libreville", actDate: "1849-06-01", legalNature: "Archive administrative", sourceLevel: "LEVEL_A", documentUrl: "https://www.archivesnationales.culture.gouv.fr/", scope: "GABON_INTERIOR" },
  { id: "archive-aef-1910", title: "Decret portant organisation de l'Afrique equatoriale francaise", actDate: "1910-01-15", legalNature: "Decret", sourceLevel: "LEVEL_A", documentUrl: "https://gallica.bnf.fr/", scope: "GABON_INTERIOR", sensitive: true },
  { id: "archive-independence-1960", title: "Accords et textes relatifs a l'independance du Gabon", actDate: "1960-08-17", legalNature: "Texte constitutionnel et archives diplomatiques", sourceLevel: "LEVEL_A", documentUrl: "https://www.un.org/", scope: "BOTH", sensitive: true },
  { id: "archive-constitution-1961", title: "Constitution de la Republique gabonaise de 1961", actDate: "1961-02-21", legalNature: "Constitution", sourceLevel: "LEVEL_A", documentUrl: "https://www.droit-afrique.com/", scope: "GABON_INTERIOR", sensitive: true },
  { id: "archive-constitution-1991", title: "Constitution gabonaise revisee de 1991", actDate: "1991-03-26", legalNature: "Constitution", sourceLevel: "LEVEL_A", documentUrl: "https://www.droit-afrique.com/", scope: "GABON_INTERIOR", sensitive: true },
  { id: "archive-national-parks-2002", title: "Decret de creation des parcs nationaux", actDate: "2002-08-30", legalNature: "Decret", sourceLevel: "LEVEL_A", documentUrl: "https://whc.unesco.org/", scope: "GABON_INTERIOR" },
  { id: "archive-unesco-lope-2007", title: "Decision UNESCO - Ecosystemes relictuels de la Lope-Okanda", actDate: "2007-07-01", legalNature: "Decision d'inscription au patrimoine mondial", sourceLevel: "LEVEL_A", documentUrl: "https://whc.unesco.org/en/list/1147", scope: "GABON_INTERIOR" },
  { id: "archive-transition-charter-2023", title: "Charte de la Transition gabonaise", actDate: "2023-09-01", legalNature: "Charte institutionnelle", sourceLevel: "LEVEL_A", documentUrl: "https://www.presidence.ga/", scope: "GABON_INTERIOR", sensitive: true },
  { id: "archive-national-dialogue-2024", title: "Rapport final du Dialogue national inclusif", actDate: "2024-05-01", legalNature: "Rapport officiel", sourceLevel: "LEVEL_A", documentUrl: "https://www.presidence.ga/", scope: "GABON_INTERIOR", sensitive: true },
];

const impacts: Array<{ id: string; figureId?: string; country: string; city?: string; period: string; domain: string; contribution: string; sourceLevel: Level; sensitive?: boolean }> = [
  { id: "impact-paris-associations", country: "France", city: "Paris", period: "1990-2020", domain: "Vie associative", contribution: "Les associations de Gabonais a Paris organisent entraide, activites culturelles et orientation administrative pour les ressortissants.", sourceLevel: "LEVEL_B" },
  { id: "impact-montreal-students", country: "Canada", city: "Montreal", period: "2000-2020", domain: "Education", contribution: "Les reseaux d'etudiants gabonais accompagnent l'accueil, le logement et l'integration universitaire de nouveaux arrivants.", sourceLevel: "LEVEL_B" },
  { id: "impact-dakar-students", country: "Senegal", city: "Dakar", period: "2000-2020", domain: "Education", contribution: "La mobilite d'etudiants gabonais vers Dakar favorise des reseaux académiques et associatifs regionaux.", sourceLevel: "LEVEL_B" },
  { id: "impact-rabat-cooperation", country: "Maroc", city: "Rabat", period: "2000-2020", domain: "Cooperation universitaire", contribution: "Les parcours d'etudiants gabonais au Maroc s'inscrivent dans des cooperations de formation et des reseaux d'entraide.", sourceLevel: "LEVEL_B" },
  { id: "impact-washington-diplomacy", country: "Etats-Unis", city: "Washington", period: "1960-2020", domain: "Diplomatie", contribution: "La representation diplomatique contribue au lien entre ressortissants, institutions gabonaises et partenaires americains.", sourceLevel: "LEVEL_A" },
  { id: "impact-brussels-culture", country: "Belgique", city: "Bruxelles", period: "1990-2020", domain: "Culture", contribution: "Les initiatives culturelles de la diaspora gabonaise font connaitre musiques, langues et traditions dans l'espace belge.", sourceLevel: "LEVEL_C" },
  { id: "impact-london-professionals", country: "Royaume-Uni", city: "Londres", period: "2000-2020", domain: "Reseaux professionnels", contribution: "Des professionnels gabonais developpent des reseaux de mentorat et de mise en relation avec le Gabon.", sourceLevel: "LEVEL_C" },
  { id: "impact-daniel-mengara-us", figureId: "figure-daniel-mengara", country: "Etats-Unis", city: "New York", period: "Annees 2000-2010", domain: "Debat public", contribution: "Les travaux et prises de parole de Daniel Mengara illustrent des contributions intellectuelles de la diaspora aux debats gabonais.", sourceLevel: "LEVEL_C", sensitive: true },
  { id: "impact-theo-kounkou-france", figureId: "figure-theo-blaise-kounkou", country: "France", city: "Paris", period: "Annees 1970-2000", domain: "Musique", contribution: "La carriere de Theo Blaise Kounkou participe a la circulation internationale de repertories musicaux gabonais.", sourceLevel: "LEVEL_B" },
  { id: "impact-laurent-owondo-france", figureId: "figure-laurent-owondo", country: "France", city: "Paris", period: "Annees 1970-2000", domain: "Litterature", contribution: "L'oeuvre de Laurent Owondo favorise la diffusion de voix litteraires gabonaises dans l'espace francophone.", sourceLevel: "LEVEL_B" },
];

async function main() {
  for (const item of events) {
    const { sensitive, ...event } = item;
    const data = { ...event, exactDate: event.exactDate ? new Date(event.exactDate) : null, relevanceDecision: relevanceDecision(event.id, event.scope, ["gabon", "historical-event"], sensitive) };
    await prisma.historicalEvent.upsert({ where: { id: item.id }, create: data, update: data });
  }
  for (const item of figures) {
    const { sensitive, ...figure } = item;
    const data = { ...figure, relevanceDecision: relevanceDecision(figure.id, figure.scope, ["gabon", "historical-figure"], sensitive) };
    await prisma.historicalFigure.upsert({ where: { id: item.id }, create: data, update: data });
  }
  for (const item of archives) {
    const { scope, sensitive, ...archive } = item;
    const data = { ...archive, actDate: archive.actDate ? new Date(archive.actDate) : null, relevanceDecision: relevanceDecision(archive.id, scope, ["gabon", "historical-archive"], sensitive) };
    await prisma.historicalArchive.upsert({ where: { id: item.id }, create: data, update: data });
  }
  for (const item of impacts) {
    const { sensitive, ...impact } = item;
    const data = { ...impact, figureId: impact.figureId ?? null, city: impact.city ?? null, relevanceDecision: relevanceDecision(impact.id, "DIASPORA", ["diaspora", impact.country], sensitive) };
    await prisma.diasporaImpact.upsert({ where: { id: item.id }, create: data, update: data });
  }

  console.log("[memoire-seed] complete:", { events: events.length, figures: figures.length, archives: archives.length, diasporaImpacts: impacts.length });
}

main().then(() => prisma.$disconnect()).catch(async (error) => { console.error(error); await prisma.$disconnect(); process.exit(1); });
