"use client";

import { useEffect, useState } from "react";

type Location = { id: string; name: string; cities: Array<{ id: string; name: string }> };
type Preferences = { countryId: string | null; cityId: string | null; memberStatus: "STUDENT" | "PROFESSIONAL" | "ENTREPRENEUR" | "ARTIST" | "OTHER"; interests: string[] };

export function PreferencesForm({ locations }: { locations: Location[] }) {
  const [preferences, setPreferences] = useState<Preferences>({ countryId: null, cityId: null, memberStatus: "OTHER", interests: [] });
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { void fetch("/api/preferences").then(async (response) => response.ok ? response.json() as Promise<{ preferences: Preferences }> : null).then((data) => { if (data) setPreferences(data.preferences); }); }, []);
  const cities = locations.find((country) => country.id === preferences.countryId)?.cities ?? [];
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(null); const response = await fetch("/api/preferences", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(preferences) }); setMessage(response.ok ? "Preferences enregistrees." : "Impossible d'enregistrer les preferences."); }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-base font-semibold text-slate-900">Mon profil de personnalisation</h2><p className="mt-2 text-sm text-slate-500">Ces criteres servent a organiser votre fil et vos alertes.</p><form onSubmit={save} className="mt-5 grid gap-4"><label className="text-sm font-medium text-slate-700">Statut<select value={preferences.memberStatus} onChange={(event) => setPreferences({ ...preferences, memberStatus: event.target.value as Preferences["memberStatus"] })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="STUDENT">Etudiant</option><option value="PROFESSIONAL">Professionnel</option><option value="ENTREPRENEUR">Entrepreneur</option><option value="ARTIST">Artiste</option><option value="OTHER">Autre</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Pays<select value={preferences.countryId ?? ""} onChange={(event) => setPreferences({ ...preferences, countryId: event.target.value || null, cityId: null })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">Non precise</option>{locations.map((country) => <option key={country.id} value={country.id}>{country.name}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Ville<select value={preferences.cityId ?? ""} disabled={!preferences.countryId} onChange={(event) => setPreferences({ ...preferences, cityId: event.target.value || null })} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm disabled:bg-slate-100"><option value="">Non precisee</option>{cities.map((city) => <option key={city.id} value={city.id}>{city.name}</option>)}</select></label></div><label className="text-sm font-medium text-slate-700">Centres d'interet<textarea value={preferences.interests.join(", ")} onChange={(event) => setPreferences({ ...preferences, interests: event.target.value.split(",").map((value) => value.trim()).filter(Boolean).slice(0, 20) })} rows={3} placeholder="Bourses, entrepreneuriat, culture, visa..." className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><div className="flex items-center gap-3"><button className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Enregistrer</button>{message ? <p role="status" className="text-sm text-slate-600">{message}</p> : null}</div></form></section>;
}