import type { SourceRegistryType } from "@/app/generated/prisma";

type SourceFormProps = {
  action: (formData: FormData) => void | Promise<void>;
  labels: Record<string, string>;
  submitLabel: string;
  initial?: { name: string; url: string; type: SourceRegistryType; country: string; language: string; rssUrl: string | null; reliability: number; termsUrl: string | null };
};

const types: SourceRegistryType[] = ["GOVERNMENT", "DIPLOMATIC", "MEDIA", "UNIVERSITY", "DIASPORA", "OTHER"];

export default function SourceForm({ action, labels, submitLabel, initial }: SourceFormProps) {
  return <form action={action} className="mt-8 space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><label className="block text-sm font-semibold text-slate-700">{labels.name}<input name="name" required defaultValue={initial?.name} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label><label className="block text-sm font-semibold text-slate-700">{labels.url}<input name="url" type="url" required pattern="https://.*" defaultValue={initial?.url} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">{labels.type}<select name="type" defaultValue={initial?.type ?? "GOVERNMENT"} className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 font-normal">{types.map((type) => <option key={type} value={type}>{labels[type.toLowerCase()]}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">{labels.country}<input name="country" required maxLength={2} defaultValue={initial?.country ?? "GA"} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">{labels.language}<input name="language" required defaultValue={initial?.language ?? "fr"} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label><label className="block text-sm font-semibold text-slate-700">{labels.reliability}<input name="reliability" type="number" min="1" max="5" step="0.1" required defaultValue={initial?.reliability ?? 3} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label></div><label className="block text-sm font-semibold text-slate-700">{labels.rssUrl}<input name="rssUrl" type="url" defaultValue={initial?.rssUrl ?? ""} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label><label className="block text-sm font-semibold text-slate-700">{labels.termsUrl}<input name="termsUrl" type="url" defaultValue={initial?.termsUrl ?? ""} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" /></label><button type="submit" className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-500">{submitLabel}</button></form>;
}