import Link from "next/link";
import { getGreAnalytics } from "@/lib/actions/gre-analytics";

function percentage(value: number, total: number) { return total ? Math.round((value / total) * 100) : 0; }

export async function GreAnalyticsDashboard() {
  const analytics = await getGreAnalytics();
  const maxTerritory = Math.max(...analytics.territories.map((item) => item.value), 1);
  return <main className="mx-auto w-full max-w-7xl flex-1 px-4 py-8 sm:px-6 sm:py-12"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-7"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-600">Observabilite</p><h1 className="mt-3 text-3xl font-semibold text-slate-900 sm:text-4xl">Gabon Relevance Engine</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Suivez la qualification GRE 2.0, les motifs de revue et la performance des sources.</p></div><Link href="/admin/content" className="text-sm font-semibold text-emerald-700 underline underline-offset-4">File de moderation</Link></header><section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Kpi label="Auto-publication, 7 j" value={`${analytics.periods.days7.autoPublishRate}%`} /><Kpi label="Revue humaine, 7 j" value={`${analytics.periods.days7.humanReviewRate}%`} /><Kpi label="Auto-publication, 30 j" value={`${analytics.periods.days30.autoPublishRate}%`} /><Kpi label="Revue humaine, 30 j" value={`${analytics.periods.days30.humanReviewRate}%`} /><Kpi label="Score GRE moyen" value={`${analytics.averageScore}/100`} /></section><section className="mt-7 grid gap-6 lg:grid-cols-2"><Panel title="Qualification par periode"><RateRow label="7 derniers jours" auto={analytics.periods.days7.autoPublishRate} review={analytics.periods.days7.humanReviewRate} total={analytics.periods.days7.total} /><RateRow label="30 derniers jours" auto={analytics.periods.days30.autoPublishRate} review={analytics.periods.days30.humanReviewRate} total={analytics.periods.days30.total} /></Panel><Panel title="Repartition territoriale">{analytics.territories.map((item) => <BarRow key={item.label} label={item.label} value={item.value} percent={percentage(item.value, maxTerritory)} />)}</Panel><Panel title="Principaux motifs GRE">{analytics.reasons.length ? analytics.reasons.map((item) => <BarRow key={item.label} label={item.label.replaceAll("_", " ")} value={item.value} percent={percentage(item.value, analytics.reasons[0].value)} />) : <Empty />}</Panel><Panel title="Performance des sources">{analytics.sourceMetrics.length ? <div className="overflow-x-auto"><table className="w-full min-w-130 text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Source</th><th className="pb-3">Cree</th><th className="pb-3">Reussite</th><th className="pb-3">Duree moy.</th></tr></thead><tbody>{analytics.sourceMetrics.map((source) => <tr key={source.name} className="border-b border-slate-100"><td className="py-3 font-medium text-slate-900">{source.name}</td><td className="py-3 text-slate-600">{source.created}/{source.fetched}</td><td className="py-3 text-slate-600">{source.successRate}%</td><td className="py-3 text-slate-600">{source.durationMs} ms</td></tr>)}</tbody></table></div> : <Empty />}</Panel></section></main>;
}

function Kpi({ label, value }: { label: string; value: string }) { return <article className="border border-slate-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold text-slate-900">{value}</p></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold text-slate-900">{title}</h2><div className="mt-5 grid gap-4">{children}</div></section>; }
function RateRow({ label, auto, review, total }: { label: string; auto: number; review: number; total: number }) { return <div><div className="flex justify-between gap-4 text-sm"><span className="font-medium text-slate-900">{label}</span><span className="text-slate-500">{total} qualifies</span></div><div className="mt-2 flex h-3 overflow-hidden bg-slate-100"><div className="bg-emerald-500" style={{ width: `${auto}%` }} /><div className="bg-amber-400" style={{ width: `${review}%` }} /></div><p className="mt-2 text-xs text-slate-600"><span className="font-semibold text-emerald-700">{auto}% auto</span> · <span className="font-semibold text-amber-700">{review}% revue humaine</span></p></div>; }
function BarRow({ label, value, percent }: { label: string; value: number; percent: number }) { return <div><div className="flex justify-between gap-4 text-sm"><span className="capitalize text-slate-700">{label}</span><span className="font-semibold text-slate-900">{value}</span></div><div className="mt-2 h-2 bg-slate-100"><div className="h-full bg-emerald-500" style={{ width: `${percent}%` }} /></div></div>; }
function Empty() { return <p className="py-5 text-sm text-slate-500">Aucune donnee GRE disponible sur cette periode.</p>; }