import "dotenv/config";
import { AdministrativeProcedureCategory, ContentModerationStatus, ProcedureContentType } from "../app/generated/prisma";
import { prisma } from "../lib/prisma";

type Procedure = { slug: string; title: string; category: AdministrativeProcedureCategory; targetAudience: string; conditions: string; requiredDocuments: string[]; estimatedDays: number; cost: string; competentAuthority: string; officialUrl: string; sourceName: string; contentType: ProcedureContentType; steps: Array<[string, string]> };
const verifiedAt = new Date("2026-09-01T00:00:00.000Z");
const consular = "Ministere des Affaires Etrangeres du Gabon et representation consulaire competente";

const procedures: Procedure[] = [
  { slug: "passeport-biometrique", title: "Passeport biometrique gabonais - premiere demande et renouvellement", category: "CONSULAR", targetAudience: "Citoyens gabonais a l'etranger ou au Gabon", conditions: "Verifier les conditions, rendez-vous et baremes en vigueur aupres de la representation competente.", requiredDocuments: ["Piece d'identite", "Acte de naissance", "Photos d'identite", "Justificatif de residence", "Ancien passeport pour un renouvellement"], estimatedDays: 30, cost: "Selon le bareme consulaire en vigueur", competentAuthority: consular, officialUrl: "https://www.diplomatie.gouv.ga/", sourceName: "Ministere des Affaires Etrangeres du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Verifier la representation", "Identifiez le consulat ou service competent."], ["Preparer les pieces", "Rassemblez les originaux et copies demandes."], ["Prendre rendez-vous", "Suivez le canal officiel de la representation."], ["Deposer et suivre", "Deposez le dossier et conservez votre recu."]] },
  { slug: "acte-naissance-retranscription", title: "Acte de naissance et retranscription d'etat civil", category: "CONSULAR", targetAudience: "Citoyens gabonais et familles ayant besoin d'un acte d'etat civil", conditions: "La procedure depend du lieu de naissance et de l'autorite detentrice de l'acte.", requiredDocuments: ["Piece d'identite", "Informations d'etat civil", "Livret de famille ou acte existant si disponible", "Justificatif de lien pour une demande tierce"], estimatedDays: 15, cost: "Selon le service competent", competentAuthority: consular, officialUrl: "https://www.diplomatie.gouv.ga/", sourceName: "Ministere des Affaires Etrangeres du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Identifier l'autorite", "Confirmez la mairie, le consulat ou le service competent."], ["Constituer le dossier", "Preparez les informations et justificatifs."], ["Soumettre la demande", "Utilisez le canal indique par l'autorite."], ["Verifier l'acte", "Controlez les donnees avant utilisation."]] },
  { slug: "carte-consulaire", title: "Carte consulaire et immatriculation", category: "CONSULAR", targetAudience: "Ressortissants gabonais etablis a l'etranger", conditions: "Resider dans la circonscription consulaire et respecter les modalites de la representation.", requiredDocuments: ["Passeport ou piece gabonaise", "Justificatif de residence", "Photo d'identite", "Formulaire consulaire"], estimatedDays: 7, cost: "Gratuit ou selon la representation", competentAuthority: consular, officialUrl: "https://www.ambassadedugabon.fr/", sourceName: "Ambassade du Gabon en France", contentType: "OFFICIAL_DOCUMENTED", steps: [["Trouver le consulat", "Identifiez la circonscription de residence."], ["Preparer les justificatifs", "Rassemblez identite et residence."], ["Remplir le formulaire", "Utilisez le formulaire fourni."], ["Faire valider", "Deposez ou transmettez selon les instructions."]] },
  { slug: "visa-entree-gabon", title: "Demande de visa d'entree au Gabon", category: "IMMIGRATION", targetAudience: "Voyageurs soumis a visa pour entrer au Gabon", conditions: "Verifier nationalite, motif de sejour, duree et exigences actualisees avant toute demande.", requiredDocuments: ["Passeport valide", "Formulaire de visa", "Photo d'identite", "Justificatif de sejour", "Billet ou itineraire", "Preuve de ressources si demandee"], estimatedDays: 15, cost: "Selon la categorie de visa et la representation", competentAuthority: "Representation diplomatique ou consulaire gabonaise competente", officialUrl: "https://www.diplomatie.gouv.ga/", sourceName: "Ministere des Affaires Etrangeres du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Verifier le visa requis", "Confirmez les exigences correspondant a votre nationalite."], ["Preparer le dossier", "Rassemblez les documents en cours de validite."], ["Deposer la demande", "Soumettez-la a la representation competente."], ["Verifier la decision", "Ne voyagez qu'apres confirmation officielle."]] },
  { slug: "bourse-anbg-premiere-demande", title: "Dossier de bourse ANBG - premiere demande", category: "INTEGRATION", targetAudience: "Etudiants gabonais candidats a une bourse", conditions: "Etre admis ou en cours d'admission selon la campagne et verifier les criteres ANBG publies.", requiredDocuments: ["Piece d'identite", "Releves et diplomes", "Lettre d'admission ou inscription", "Projet d'etudes", "Pieces demandees par la campagne"], estimatedDays: 45, cost: "Selon les conditions de la campagne", competentAuthority: "ANBG - Agence Nationale des Bourses du Gabon", officialUrl: "https://www.dgbc.gouv.ga/", sourceName: "ANBG - Agence Nationale des Bourses du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Lire l'appel", "Verifiez calendrier, niveaux et criteres."], ["Preparer le dossier", "Rassemblez les justificatifs academiques."], ["Deposer", "Soumettez par le portail ou canal officiel."], ["Suivre la campagne", "Conservez les preuves et consultez les resultats."]] },
  { slug: "bourse-anbg-renouvellement-transfert", title: "Renouvellement ou transfert de bourse ANBG", category: "INTEGRATION", targetAudience: "Boursiers gabonais souhaitant renouveler ou transferer leur dossier", conditions: "Respecter les resultats academiques et les conditions de la campagne de renouvellement ou transfert.", requiredDocuments: ["Attestation d'inscription", "Resultats academiques", "Attestation de bourse", "Justificatif de transfert si applicable"], estimatedDays: 30, cost: "Selon les conditions de la campagne", competentAuthority: "ANBG - Agence Nationale des Bourses du Gabon", officialUrl: "https://www.dgbc.gouv.ga/", sourceName: "ANBG - Agence Nationale des Bourses du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Verifier l'eligibilite", "Consultez les conditions de renouvellement."], ["Obtenir les resultats", "Rassemblez les releves demandes."], ["Declarer le transfert", "Ajoutez les justificatifs de changement d'etablissement."], ["Suivre la decision", "Consultez les communications officielles."]] },
  { slug: "campus-france-titre-sejour-etudiant", title: "Procedure Campus France et titre de sejour etudiant", category: "INTEGRATION", targetAudience: "Etudiants gabonais preparant un projet d'etudes en France", conditions: "Respecter les etapes Campus France, les exigences de l'etablissement et celles de l'administration francaise.", requiredDocuments: ["Passeport", "Admission", "Diplomes et releves", "Justificatif de ressources", "Justificatif de logement"], estimatedDays: 60, cost: "Selon Campus France et les frais administratifs applicables", competentAuthority: "Campus France, consulat de France et prefecture competente", officialUrl: "https://www.campusfrance.org/", sourceName: "Campus France", contentType: "GABONCONNECT_EXPLANATORY", steps: [["Creer le dossier Campus France", "Suivez les instructions de la plateforme officielle."], ["Obtenir l'admission", "Conservez les preuves d'admission."], ["Demander le visa", "Deposez le dossier consulaire conforme."], ["Regler le sejour", "Effectuez les formalites apres arrivee."]] },
  { slug: "attestation-non-boursier-scolarite", title: "Attestation de non-boursier et certificat de scolarite", category: "INTEGRATION", targetAudience: "Etudiants constituant un dossier administratif ou de bourse", conditions: "Confirmer le format et la periode attendus par l'organisme demandeur.", requiredDocuments: ["Piece d'identite", "Carte etudiante ou inscription", "Formulaire ou demande de l'organisme"], estimatedDays: 14, cost: "Selon l'organisme emetteur", competentAuthority: "DGBC, ANBG ou etablissement d'enseignement competent", officialUrl: "https://www.dgbc.gouv.ga/", sourceName: "DGBC - Direction Generale des Bourses du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Identifier le document", "Confirmez l'attestation demandee."], ["Preparer les preuves", "Rassemblez identite et inscription."], ["Soumettre", "Adressez la demande au service competent."], ["Verifier la validite", "Controlez les dates et mentions."]] },
  { slug: "creation-entreprise-anpi", title: "Creation d'entreprise au Gabon - Guichet Unique ANPI", category: "INTEGRATION", targetAudience: "Porteurs de projet et entrepreneurs creant une activite au Gabon", conditions: "Choisir la forme juridique et verifier les formalites applicables au projet.", requiredDocuments: ["Piece d'identite", "Projet de statuts", "Adresse du siege", "Informations sur les associes", "Documents demandes par le Guichet Unique"], estimatedDays: 15, cost: "Selon forme juridique et formalites applicables", competentAuthority: "ANPI Gabon - Guichet Unique", officialUrl: "https://anpi.ga/", sourceName: "ANPI Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Definir le projet", "Choisissez la forme juridique adaptee."], ["Preparer les statuts", "Constituez les documents de creation."], ["Deposer au Guichet Unique", "Soumettez le dossier selon les instructions ANPI."], ["Suivre l'immatriculation", "Recuperez les preuves d'enregistrement."]] },
  { slug: "legalisation-certification-documents", title: "Legalisation et certification de documents", category: "CONSULAR", targetAudience: "Usagers devant faire reconnaitre des documents gabonais a l'etranger", conditions: "Verifier si l'organisme destinataire exige certification, legalisation ou autre formalite.", requiredDocuments: ["Document original", "Copies", "Piece d'identite", "Justificatif de demande si requis"], estimatedDays: 12, cost: "Selon document et representation", competentAuthority: consular, officialUrl: "https://www.diplomatie.gouv.ga/", sourceName: "Ministere des Affaires Etrangeres du Gabon", contentType: "OFFICIAL_DOCUMENTED", steps: [["Verifier l'exigence", "Confirmez la formalite demandee."], ["Preparer les originaux", "Rassemblez originaux et copies."], ["Deposer", "Adressez-vous au service competent."], ["Verifier le document", "Controlez cachet et signature avant usage."]] },
];

async function main() {
  await prisma.administrativeProcedure.updateMany({
    where: { slug: { notIn: procedures.map((procedure) => procedure.slug) }, archivedAt: null },
    data: { archivedAt: new Date() },
  });
  for (const data of procedures) {
    const { steps, ...procedureData } = data;
    const persisted = { ...procedureData, description: `${data.title}. ${data.conditions}`, moderationStatus: ContentModerationStatus.APPROVED, publishedAt: new Date(), canonicalUrl: data.officialUrl, copyrightFlag: true, verifiedAt };
    const procedure = await prisma.administrativeProcedure.upsert({ where: { slug: data.slug }, update: persisted, create: persisted });
    await prisma.procedureStep.deleteMany({ where: { procedureId: procedure.id } });
    await prisma.procedureStep.createMany({ data: steps.map(([title, description], index) => ({ procedureId: procedure.id, order: index + 1, title, description, isRequired: true })) });
  }
  console.log("[seed-flagship-procedures]", { upserted: procedures.length, verifiedAt: verifiedAt.toISOString() });
}

main().then(() => prisma.$disconnect()).catch(async (error) => { console.error(error); await prisma.$disconnect(); process.exit(1); });