import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { getLocale, getMessages } from "@/lib/i18n";
import { getHousingOffers, getScholarships } from "@/lib/actions/campus";
import { ScholarshipLevel, HousingType } from "@/app/generated/prisma";
import HousingOfferForm from "@/components/campus/housing-offer-form";
import AggregatedAlerts from "@/components/aggregation/aggregated-alerts";
import { getAggregatedAlerts } from "@/lib/aggregation/public-alerts";

type CampusPageProps = { searchParams: Promise<{ tab?: string; level?: string; country?: string; provider?: string; city?: string; type?: string }> };

export const dynamic = "force-dynamic";

export default async function CampusPage({ searchParams }: CampusPageProps) {
  const user = await getCurrentUser();
  if (!user) redirect("/login?redirectTo=/dashboard/campus");
  const locale = await getLocale();
  const messages = getMessages(locale);
  const params = await searchParams;
  const tab = params.tab === "housing" || params.tab === "guide" ? params.tab : "scholarships";
  const level = Object.values(ScholarshipLevel).includes(params.level as ScholarshipLevel) ? params.level as ScholarshipLevel : undefined;
  const type = Object.values(HousingType).includes(params.type as HousingType) ? params.type as HousingType : undefined;
  const [scholarships, housing, alerts] = await Promise.all([getScholarships({ level, country: params.country, provider: params.provider }), getHousingOffers({ city: params.city, country: params.country, type }), getAggregatedAlerts({ categories: ["CAMPUS", "OPPORTUNITIES"], limit: 6 })]);

  return (
    <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-8 sm:px-6 sm:py-12">
      <header><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-600">Campus 2.0</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">{messages.campus.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{messages.campus.intro}</p></header>
      <AggregatedAlerts articles={alerts} messages={messages} />
      <nav aria-label={messages.campus.title} className="mt-8 flex gap-2 overflow-x-auto border-b border-slate-200"><Tab href="?tab=scholarships" active={tab === "scholarships"}>{messages.campus.scholarships}</Tab><Tab href="?tab=housing" active={tab === "housing"}>{messages.campus.housing}</Tab><Tab href="?tab=guide" active={tab === "guide"}>{messages.campus.guide}</Tab></nav>

      {tab === "scholarships" && <section className="pt-8"><form method="get" className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-4"><input type="hidden" name="tab" value="scholarships" /><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.country}<input name="country" defaultValue={params.country} placeholder={messages.campus.allCountries} className="rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.provider}<input name="provider" defaultValue={params.provider} placeholder={messages.campus.allProviders} className="rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.level}<select name="level" defaultValue={level ?? ""} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-normal"><option value="">{messages.campus.allLevels}</option>{Object.values(ScholarshipLevel).map((item) => <option key={item} value={item}>{messages.campus[item.toLowerCase() as keyof typeof messages.campus]}</option>)}</select></label><button type="submit" className="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">{messages.common.search}</button></form><div className="mt-6 grid gap-5 md:grid-cols-2">{scholarships.length === 0 ? <Empty text={messages.campus.noScholarships} /> : scholarships.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><span className="font-semibold text-emerald-700">{item.provider}</span><span className="text-xs text-slate-500">{item.country}</span></div><h2 className="mt-3 text-xl font-semibold text-slate-900">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p><p className="mt-4 text-sm text-slate-700"><strong>{messages.campus.eligibility}:</strong> {item.eligibilityCriteria}</p><p className="mt-3 text-sm font-semibold text-red-700">{messages.campus.deadline}: {item.deadline.toLocaleDateString(locale === "fr" ? "fr-FR" : "en-US")}</p><a href={item.applicationUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">{messages.campus.apply}</a></article>)}</div></section>}
      {tab === "housing" && <section className="pt-8"><form method="get" className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-4"><input type="hidden" name="tab" value="housing" /><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.city}<input name="city" defaultValue={params.city} className="rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.country}<input name="country" defaultValue={params.country} className="rounded-lg border border-slate-200 px-3 py-2 font-normal" /></label><label className="flex flex-col gap-1 text-sm font-medium text-slate-700">{messages.campus.housingType}<select name="type" defaultValue={type ?? ""} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-normal"><option value="">{messages.campus.housingType}</option>{Object.values(HousingType).map((item) => <option key={item} value={item}>{messages.campus[item.toLowerCase() as keyof typeof messages.campus]}</option>)}</select></label><button type="submit" className="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">{messages.common.search}</button></form><div className="mt-6 grid gap-5 md:grid-cols-2">{housing.length === 0 ? <Empty text={messages.campus.noHousing} /> : housing.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><span className="font-semibold text-emerald-700">{messages.campus[item.type.toLowerCase() as keyof typeof messages.campus]}</span><span className="text-sm font-semibold text-slate-900">{item.price}</span></div><h2 className="mt-3 text-xl font-semibold text-slate-900">{item.city}, {item.country}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p><p className="mt-4 text-xs text-slate-500">{item.author.profile ? `${item.author.profile.firstName} ${item.author.profile.lastName}` : messages.common.contact}</p><a href={`mailto:${item.contactEmail}`} className="mt-4 inline-flex rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">{messages.campus.contact}</a></article>)}</div><HousingOfferForm labels={messages.campus} /></section>}
      {tab === "guide" && <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-semibold text-slate-900">{messages.campus.guide}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{messages.campus.guideIntro}</p><ol className="mt-6 grid gap-3 sm:grid-cols-2">{messages.campus.guideItems.map((item, index) => <li key={item} className="rounded-xl bg-slate-50 p-4 text-sm text-slate-700"><span className="font-semibold text-emerald-700">{index + 1}. </span>{item}</li>)}</ol><Link href="/dashboard/procedures?category=INTEGRATION" className="mt-6 inline-flex rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">{messages.procedures.title}</Link></section>}
    </main>
  );
}

function Tab({ href, active, children }: { href: string; active: boolean; children: React.ReactNode }) { return <Link href={href} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-semibold ${active ? "border-emerald-600 text-emerald-700" : "border-transparent text-slate-500 hover:text-slate-800"}`}>{children}</Link>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500 md:col-span-2">{text}</p>; }
